from PySide6.QtWidgets import QWidget, QVBoxLayout, QTextBrowser

class HelpTab(QWidget):
    def __init__(self):
        super().__init__()
        layout = QVBoxLayout()
        
        self.browser = QTextBrowser()
        self.browser.setOpenExternalLinks(True)
        
        html_content = """
        <h2>MT5 Strategy Console - Help & Documentation</h2>
        
        <h3>Philosophy</h3>
        <p>This application is designed as a strict Read-Only analysis tool. It will <b>never</b> execute, modify, or close trades automatically. The core philosophy is:<br>
        <i>MARKET DATA &rarr; USER DEFINED RULES &rarr; DETERMINISTIC EVALUATION &rarr; OBSERVABLE SIGNAL &rarr; HUMAN DECISION</i></p>

        <h3>Dashboard</h3>
        <ul>
            <li><b>Status:</b> Shows if the connection to your local MT5 terminal is active.</li>
            <li><b>Active Strategy:</b> The currently loaded strategy being evaluated against incoming price data.</li>
            <li><b>Signal Journal:</b> A log of all signals generated by your strategy.</li>
        </ul>

        <h3>Strategy Builder (Full Control)</h3>
        <p>The Strategy Builder allows you to construct logic without constraints. It uses a Split-View design:</p>
        <ul>
            <li><b>Visual Editor (Left):</b> Easily construct rules using the dropdowns. You can load existing strategies to edit them.</li>
            <li><b>JSON Editor (Right):</b> For absolute control, you can type your strategy directly into the text box. The JSON format is transparent and any changes you make will sync to the visual editor.</li>
        </ul>

        <h3>Monitor</h3>
        <p>Once your strategy is built, go to the Monitor tab. Load your strategy and click "Start Monitoring". The engine will evaluate the rules against real-time closing candles.</p>

        <h3>Bot Observer</h3>
        <p>This is a specialized tracking tool designed to audit existing EAs running on your MT5 terminal.</p>
        <ul>
            <li><b>Target Magic Number:</b> Every bot attaches a 'Magic Number' to its trades. If you know the bot's magic number, enter it here to filter observations so you only see activity from that specific bot. Leave blank to observe all manual and bot trades on the account.</li>
            <li><b>CSV Output:</b> All observations are saved in <i>data/observations/xauusd_trial_activity.csv</i>.</li>
        </ul>
        """
        self.browser.setHtml(html_content)
        
        layout.addWidget(self.browser)
        self.setLayout(layout)
